API_DEPS = [
    "fastapi",
    "alembic",
    "uvicorn[standard]",
    "sqlalchemy[asyncio]",
    "asyncpg",
    "pydantic[email]",
    "pyjwt",
    "pwdlib[argon2]",
    "redis",
    "python-dotenv",
    "python-multipart",
    "greenlet",
    "rich",
]
